baseURL = "https://new-wayland.com/blog/"
title = "New Wayland"
theme = "ghostwriter"
languageCode = "en-gb"
copyright = "New Wayland"
pygmentsUseClasses = true
pygmentsCodeFences = true

[Author]
    name = "NeilW"

[Params]
    mainSections = ["post"]
    opengraph = true
    dateFormat = "_2 Jan 2006 15:04 -0700"
    intro = true
    headline = "New Wayland Blog"
    description = "Welcome to the Future"
    github = "https://github.com/newwayland"
    reddit = "https://www.reddit.com/user/aldursys"
    email = "modernmoneymatters@protonmail.com"
    discord = "https://discord.gg/ESGqEsv"
    shareGooglePlus = false
    shareLinkedIn = true

[Permalinks]
    post = "/:filename/"
